
name: CI-CD

on:
  push:
env:
    docker_image: fabricioveronez/nodejs-web

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}

    - name: Construção da imagem Docker worker
      uses: docker/build-push-action@v5
      with: 
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          "${{ env.docker_image }}:${{github.run_number}}"
          "${{ env.docker_image }}:latest"  

  deploy-homologacao:
    needs: [CI]
    uses: fabricioveronez/nodejs-web/.github/workflows/deploy.yaml@main
    with:
      docker_image: "${{ env.docker_image }}:${{github.run_number}}"
      ambiente: homologacao

  deploy-producao:
        needs: [CI]
        uses: fabricioveronez/nodejs-web/.github/workflows/deploy.yaml@main
        with:
          docker_image: "${{ env.docker_image }}:${{github.run_number}}"
          ambiente: producao